# Generated by Django 5.0 on 2025-07-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_address_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
